version: '3.8'

services:
  pnid-detector:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./main_driver:/app/main_driver"
      - "./logs:/app/logs"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 